In [1]:
import numpy as np


In [3]:
arr1=np.linspace(-np.pi,np.pi,10)
arr1

array([-3.14159265, -2.44346095, -1.74532925, -1.04719755, -0.34906585,
        0.34906585,  1.04719755,  1.74532925,  2.44346095,  3.14159265])

In [ ]:

sin_values=np.sin(arr1) 
sin_values


array([-1.22464680e-16, -6.42787610e-01, -9.84807753e-01, -8.66025404e-01,
       -3.42020143e-01,  3.42020143e-01,  8.66025404e-01,  9.84807753e-01,
        6.42787610e-01,  1.22464680e-16])

USING MEAN IN NUMPY ARRAY

In [34]:
arr1=np.array([1,5,7,8])
mean=np.mean(arr1)
mean

np.float64(5.25)

In [45]:
arr2=np.array([[6,7,8,10],[8,3,5,12],[10,23,4,6],[10,12,16,18]])
mean1=np.mean(arr2,axis=0)  #column wise mean
mean2=np.mean(arr2,axis=1)  #row wise mean
print(mean1)
print(mean2)


[ 8.5  11.25  8.25 11.5 ]
[ 7.75  7.   10.75 14.  ]


random number in py


In [57]:
#rand
#randint
arr3=np.random.randint(3,10,size=(4,4))
arr3

array([[3, 7, 8, 3],
       [8, 5, 9, 4],
       [9, 6, 7, 4],
       [7, 6, 5, 8]], dtype=int32)