In [25]:
import numpy as np


Concatenation of array


In [26]:
arr1=np.array([[1,2,3,4]])
arr2=np.array([[3,3,3,3]])  
arr3=np.concatenate((arr1,arr2)) ##axis1,column wise axis0,row wise
print(arr3)

[[1 2 3 4]
 [3 3 3 3]]


In [27]:
arr4=np.concatenate((arr1,arr2),axis=1)
print(arr4)

[[1 2 3 4 3 3 3 3]]


In [ ]:
arr5=np.array([[1,2,3],[4,5,6]])