In [4]:
import numpy as np


In [5]:
arr1=np.array([3,5,6,8,10])
print(arr1)
print(type(arr1))

[ 3  5  6  8 10]
<class 'numpy.ndarray'>


In [6]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3)
print("Number of dimensions:", arr3.ndim)
print("Shape of array:", arr3.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Number of dimensions: 3
Shape of array: (2, 2, 3)


In [8]:
arr_100=np.arange(0,101,2)
print(arr_100)


[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [9]:
###linspace
arr_lin=np.linspace(1,10,10)
print(arr_lin)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [10]:
###creating zero,ones and identity matrix
arr_zeros=np.zeros((8,8))
print(arr_zeros)
arr_ones=np.ones((8,8),dtype=int)
print(arr_ones)
arr_eye=np.eye(8)
print(arr_eye)
print(arr_eye.shape)


[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
(8, 8)


In [11]:
arr1=np.array([[1,2,3,4,5],[1,2,3,4,5]])
arr2=np.array([[3,6,7,8,9],[6,7,8,9,10]])
print(arr1*arr2)

[[ 3 12 21 32 45]
 [ 6 14 24 36 50]]


In [12]:
arr1=np.array([[1,2],[1,2]])
arr2=np.array([[3,6],[6,7]])
print(arr1 @ arr2)

[[15 20]
 [15 20]]


In [13]:
arr1=np.array([2,3,4,5],ndmin=5)
arr1
arr1.shape

(1, 1, 1, 1, 4)

In [14]:
###operations in array
arr1=np.array([4,8,9,12])
print(arr1+10)
##vectorizations in numpy array

[14 18 19 22]


In [15]:
##slicing in np array
print(arr1[1])
##indexing in 2d array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

arr2[1][1]

8
[[1 2 3]
 [4 5 6]]


np.int64(5)

In [16]:
#slicing in numpy array
print(arr2[0:2,0:4])
#array2[startrow:endrow , startcol:end col]

[[1 2 3]
 [4 5 6]]


In [18]:
###reshaping an array
arr1=np.array([[1,2,3,10],[4,5,6,12],[7,8,9,13]])
arr2=arr1.reshape(4,3)
print(arr2)



[[ 1  2  3]
 [10  4  5]
 [ 6 12  7]
 [ 8  9 13]]


In [34]:
#to store 100 elements in 2d matrix in shape of 5,20
arr1=np.array([i for i in range(1,101)])
arr2=arr1.reshape(5,20)
print(arr2)
 

[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
   19  20]
 [ 21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38
   39  40]
 [ 41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58
   59  60]
 [ 61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78
   79  80]
 [ 81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98
   99 100]]
