In [25]:
import numpy as np


Concatenation of array


In [26]:
arr1=np.array([[1,2,3,4]])
arr2=np.array([[3,3,3,3]])  
arr3=np.concatenate((arr1,arr2)) ##axis1,column wise axis0,row wise
print(arr3)

[[1 2 3 4]
 [3 3 3 3]]


In [27]:
arr4=np.concatenate((arr1,arr2),axis=1)
print(arr4)

[[1 2 3 4 3 3 3 3]]


In [31]:
arr5=np.array([[4,5,6,8],[9,9,9,9]])
arr6=np.array([[6,6,6,6],[1,1,1,1]])
np.concatenate((arr5,arr6),axis=1)
np.concatenate((arr5,arr6),axis=0)

array([[4, 5, 6, 8],
       [9, 9, 9, 9],
       [6, 6, 6, 6],
       [1, 1, 1, 1]])

Vstack() hstack()

In [40]:
np.vstack((arr1,arr2))


array([[1, 2, 3, 4],
       [3, 3, 3, 3]])

In [39]:
np.hstack((arr1,arr2))

array([[1, 2, 3, 4, 3, 3, 3, 3]])