In [1]:
import numpy as np


In [3]:
arr1=np.array([3,5,6,8,10])
print(arr1)
print(type(arr1))

[ 3  5  6  8 10]
<class 'numpy.ndarray'>


In [7]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3)
print("Number of dimensions:", arr3.ndim)
print("Shape of array:", arr3.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Number of dimensions: 3
Shape of array: (2, 2, 3)


In [15]:
arr_100=np.arange(0,101,2)
print(arr_100)


[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [18]:
###linspace
arr_lin=np.linspace(1,10,10)
print(arr_lin)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [28]:
###creating zero,ones and identity matrix
arr_zeros=np.zeros((8,8))
print(arr_zeros)
arr_ones=np.ones((8,8),dtype=int)
print(arr_ones)
arr_eye=np.eye(8)
print(arr_eye)
print(arr_eye.shape)


[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
(8, 8)


In [33]:
arr1=np.array([[1,2,3,4,5],[1,2,3,4,5]])
arr2=np.array([[3,6,7,8,9],[6,7,8,9,10]])
print(arr1*arr2)

[[ 3 12 21 32 45]
 [ 6 14 24 36 50]]


In [42]:
arr1=np.array([[1,2],[1,2]])
arr2=np.array([[3,6],[6,7]])
print(arr1 @ arr2)

[[15 20]
 [15 20]]
